version: "3"
services:
  db:
    image: mysql:8.0.30
    restart: always
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

    container_name: spring_batch
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=spring_batch
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul